const express = require("express");
const helmet = require("helmet");
const morgan = require("morgan");
const cors = require("cors");
require("dotenv").config();
const app = express();
app.use(cors());
app.use(helmet());
app.use(morgan("dev"));
app.disable("x-powered-by");
app.use(express.json({ limit: "100mb" }));
app.use(express.urlencoded({ extended: true, limit: "100mb" }));
require("./app/routes/index.route")(app);
const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`listening on port ${port}`));
